### ISSUE TITLE
Empty Model

### ISSUE THREAD

**Issue by nstogner** [substratusai/models#4]
Thinking it might make sense to add an "empty" model that would serve as a starting point for building a model from scratch.

**Comment by nstogner** [comment]
Perhaps an "empty-pytorch" model that is ready to be trained, and wired up for serving already.

**Comment by samos123** [comment]
I think that makes sense maybe if a notebook doesn't specify a model then it would use the default empty model?

**Comment by brandonjbjelland** [comment]
The recent redesign renders this issue moot. Closing but reopen if you see a need.
